version: '3'
services:
  mockopenai: # interface
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/v1/models
      interval: 5s
      timeout: 5s
      retries: 5      
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_REPO=${GITHUB_REPO}
    image: h4ckermike/mockopenai
    ports:
      -  "8080:5000"

  autogpt: #the beast
    entrypoint: |
      bash -c "poetry run autogpt --install-plugin-deps    --skip-news   --ai-name '${AI_NAME}'    --ai-role '${AI_ROLE}'   --ai-goal '${AI_GOAL_1}'    --ai-goal '${AI_GOAL_2}'    --ai-goal '${AI_GOAL_3}'   --ai-goal '${AI_GOAL_4}'    -y --continuous           --continuous-limit 1"

    # uncomment thse next 3 lines for debugging
    #entrypoint: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    environment:
      - GITHUB_PAT="${GITHUB_PAT}"
      - AI_NAME="${AI_NAME}"
      - AI_ROLE="${AI_ROLE}"
      - AI_GOAL_1="${AI_GOAL_1}"
      - AI_GOAL_2="${AI_GOAL_2}"
      - AI_GOAL_3="${AI_GOAL_3}"
      - AI_GOAL_4="${AI_GOAL_4}"
      - GITHUB_REPO="meta-introspector/call-auto-gpt"
      - OPENAI_API_KEY=your-openai-api-key
      #- OPENAI_API_BASE=http://mockopenai:8080/v1
      - OPENAI_API_BASE=http://host.containers.internal:8080/v1
    image: h4ckermike/autogpt
    depends_on:
      - mockopenai
