name: AUTOGPT
on:
  # workflow_dispatch :   #only run when requested
  # issue_comment:
  #  types: [created]

jobs:
  printEnv:
    permissions: write-all
      # repository:write      
    name: Print env
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          echo TEST ${{ contains(fromJson('["nektos/act", "jmikedupont2", "Mysticmarks"]'), github.actor ) }}
          echo USER "$GITHUB_USER"
          echo USER "$GITHUB_REPO"
          echo ACTOR    "${{ github.actor }}"
          echo TRIGGER  "${{ github.triggering_actor }}"
          echo LOGIN    "${{ github.event.comment.user.login }}"

  runJob:
    permissions: write-all
    name: Runevent
    runs-on: ubuntu-latest
    #if: ${{ contains(fromJson('[ "nektos/act", "jmikedupont2", "Mysticmarks", "amonkhepri" ]'), github.actor ) }}
    #if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    #if: contains(github.event.comment.body, '/support')   # check the
    if: startsWith(${{ github.event.comment.body }}, '/agent-action')
runs-on: [ubuntu-latest]
    steps:
      - name: run gh workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson (github) }}
          GITHUB_USER: ${{ github.event.comment.user.login }}
          GITHUB_REPO: ${{ github.repository }}
          COMMENT_BODY: $${{ github.event.comment.body }}
        run: |
          echo TEST ${{ contains(fromJson('["nektos/act", "jmikedupont2", "Mysticmarks"]'), github.actor ) }}
          echo USER "$GITHUB_USER"
          echo USER "$GITHUB_REPO"
          echo ACTOR    "${{ github.actor }}"
          #echo TRIGGER  "${{ github.triggering_actor }}"
          #echo LOGIN    "${{ github.event.comment.user.login }}"
          #echo $GITHUB_CONTEXT | gh workflow run  -R jmikedupont2/ai-ticket run.yml \
          #   --ref docker-live-source-no-build || echo skip
          # call an another repo
          # echo $GITHUB_CONTEXT | gh workflow run -R meta-introspector/ai-ticket run.yml  || echo done
          
          # call in our own repo
          #echo $GITHUB_CONTEXT | 
          gh workflow run \
              -f ai_name=github_seer \
              -f ai_role=githubactionexpert \
              -f ai_goal_1="write github actions" \
              -f ai_goal_2="get user input" \
              -f ai_goal_3="debug errors" \
              -f ai_goal_4="$comment_body" \
              -f ai_goal_count=4 \
              -R meta-introspector/call-auto-gpt run.yml  || echo done

